# Generated by Django 3.2.3 on 2021-07-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0003_gpshistoricaldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastorage',
            name='device_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
