# Generated by Django 3.2.3 on 2021-07-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0004_datastorage_device_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datastorage',
            old_name='device_id',
            new_name='deviceid',
        ),
        migrations.AlterField(
            model_name='datastorage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
